---
title: "LOS_AdmitDirectly"
author: "Sulagna Patra"
date: "3/14/2021"
output: html_document
---
    
    
```{r Setup and DB Connection, include=FALSE}
source("1_setup_environment.R")
library(dataMaid)
library(DBI)
library(flextable)
```

##Data Analysis for Member_History Table  
```{r,include= FALSE}
con <- DBI::dbConnect(odbc::odbc(), 
                      Driver = "SQL Server", 
                      Server =  "pcnjdevsql02",
                      Database = "PIE_Dev",
                      Trusted_Connection = "True")
dbListTables(con)

dbGetInfo(con)
```

```{r}
# tbl_long_cols_2 <- function(con, table) {
#     cols_sorted <-
#         odbc::odbcConnectionColumns(con, table) %>%
#         dplyr::arrange(column_size) %>%
#         pull(name)
# 
#     dplyr::tbl(con, table) %>%
#         dplyr::select(tidyselect::all_of(cols_sorted))
# }
# AdmitDirectlyOOH<- tbl_long_cols_2(con, "RSPM_AdmitDirectlyOOH")%>%
#     collect()
```
##Pulling RSPM_LOS_AdmitDirectlyOOH Table
```{r, include= FALSE}
tbl_long_cols_2 <- function(con, table) {
    cols_sorted <-
        odbc::odbcConnectionColumns(con, table) %>%
        dplyr::arrange(column_size) %>%
        pull(name)
    
    dplyr::tbl(con, table) %>%
        dplyr::select(tidyselect::all_of(cols_sorted))
}
AdmitDirectlyOOH_LOS<- tbl_long_cols_2(con, "RSPM_LOS_AdmitDirectlyOOH")%>%
    collect()
```

##This Informations are from AdmitDirectlyOOH_LOS table which contain AdmitDirectly for the members

##Total number of admission to OOH Placement and their mean, Median and Mode

```{r}
summary(AdmitDirectlyOOH_LOS$LOS)
# mean(df_los$lengthofstay)
boxplot(AdmitDirectlyOOH_LOS$LOS , data=AdmitDirectlyOOH_LOS)
hist(AdmitDirectlyOOH_LOS$LOS,xlim=c(-60,1769), breaks=10,col="green", freq = FALSE)
#abline(v = 12, lwd = 2)
abline(v = median(AdmitDirectlyOOH_LOS$LOS), col = "magenta", lwd = 4)
x <- seq(-60, 1769, length.out=1000)
y <- with(AdmitDirectlyOOH_LOS, dnorm(x, mean(LOS), sd(LOS)))
lines(x, y, col = "red")
````
```{r, mode of AdmitDirectlyOOH}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

getmode(AdmitDirectlyOOH_LOS$LOS)
names(table(AdmitDirectlyOOH_LOS$LOS))[table(AdmitDirectlyOOH_LOS$LOS)==max(table(AdmitDirectlyOOH_LOS$LOS))]
```
## Total Number of Admission by each member and mean LOS
```{r, Each Member LOS1}
LOS_permember<-AdmitDirectlyOOH_LOS %>%
           group_by(memberid)%>%
        summarise(count=n(),Max_LOS=max(LOS),Min_LOS=min(LOS),Avg_LOS=mean(LOS),.groups = 'drop')%>%
    arrange(desc(count))
  LOS_permember<-data.frame( LOS_permember)
  LOS_permember
```
```{r, Each Member LOS on Average LOS}
summary(LOS_permember$Avg_LOS)
#plot(Avg_LOS~ count, data=LOS_permember)
ggplot(LOS_permember, aes(x=Avg_LOS, y=count)) + geom_point()
 hist(LOS_permember$Avg_LOS,xlim=c(0,1500), breaks=10,col="green", freq = FALSE)
#abline(v = 12, lwd = 2)
abline(v = median(LOS_permember$Avg_LOS), col = "magenta", lwd = 4)
```